### ISSUE TITLE
Could you please add the 'Hacktoberfest' topic to this repository?

### ISSUE THREAD

**Issue by SomSingh23** [gdsc-kits/hacktober2023#22]
![image](https://github.com/gdsc-kits/hacktober2023/assets/91485305/50fe73a4-2bc0-433f-a42a-1e7a218397d5)

**Comment by gdsc-kits-admin** [comment]
Hey this repository is not officially part of Hacktoberfest 2023, this is for first-time contributors at Karunya University to practice hands-on. Sorry for the inconvenience.
Next year we are officially planning to be a part of Hacktoberfest see you then!
Thank you.
